ALTER TABLE categories ADD COLUMN IF NOT EXISTS section VARCHAR(20) DEFAULT 'other';

CREATE TABLE IF NOT EXISTS hero_images (
  id SERIAL PRIMARY KEY,
  photo_id INTEGER REFERENCES photos(id) ON DELETE CASCADE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
